ci: separate api tests from style/type checking to avoid server overload - fix(grpc,test): increase read timeout for follow flight endpoint - ci(json): make all pydantic type adapters strict to increase typeddict correctness - fix: playback, flight_list typeddict schema - remove!: cached static data files in repo

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -10,10 +10,10 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  build:
+  style-check:
+    name: "style and type checking"
+    if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && (github.event.pull_request.head.repo.fork || startsWith(github.head_ref, 'dependabot/')))
     runs-on: ${{ matrix.platform }}
-    # avoid duplicate tests when pushing commits to PRs
-    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
     strategy:
       fail-fast: false
       matrix:
@@ -47,6 +47,29 @@ jobs:
 
       - name: Type checking
         run: uv run mypy src tests docs/usage/scripts
+
+  # NOTE: we intentionally isolate the API tests from style/type checking because
+  # the matrix above runs everything in parallel on the same machine,
+  # causing server overload and a bunch of failed tests.
+  # Pinning to a singular 3.13 instance here.
+  test:
+    name: "api testing"
+    if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && (github.event.pull_request.head.repo.fork || startsWith(github.head_ref, 'dependabot/')))
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Install uv
+        uses: astral-sh/setup-uv@v3
+        with:
+          enable-cache: true
+
+      - uses: actions/setup-python@v5
+        with:
+          python-version: "3.13"
+
+      - name: Install the project
+        run: uv sync
 
       - name: Run tests
         run: uv run pytest
